%#!platex jou.tex

\newcommand*\MakeTabSkip{\hbox to 5em{\rightarrowfill}}

{\LaTeX}は{コンパイル型}の言語です．

ソースファイルを{\LaTeX}プログラムに渡せば人間が読める媒体に変換します．
この{\LaTeX}のソースファイルに対して\Prog{Make}と呼ばれるプログラムを使
うことで原稿の再コンパイルを支援してくれます．これは一つのグループになっ
たソースファイルを依存関係をはっきりとさせて，再コンパイルを自動化するプ
ログラムです．

Makeは\unixos 主流のプログラムですから，Unix系OSでなければ実行させるのが
難しいかもしれません．あなたのOSがGNU Linuxならば簡単にインストールでき
るはずです．Windowsの方は\prog{Cygwin}と呼ばれるWindows上で動作させるこ
とができる擬似Unix環境がありますのでこれを導入してみてください．

コンソールなどから次のように
\begin{InTerm}
   \type{make} 
\end{InTerm}
とすれば
\begin{OutTerm}
make: *** No targets specified and no makefile found.  Stop.
\end{OutTerm}
の表示が出るでしょう．ゲームを始める準備は整
っているようです．表示されないならば，近くの
詳しい人に聞いてみましょう．

まずは簡単な例を示しますので，\prog{Make}の基本を見てみましょう．
\begin{Makefile}
all: file.dvi
file.dvi: file.tex
	platex file
\end{Makefile}
これは以下のような文法に則り記述されています．
\begin{Syntax}
\verb|all:| \va{結果的に作りたいもの}\\
\va{作りたいもの}: \va{それに依存するもの}\\
\MakeTabSkip 処理内容
\end{Syntax}
上記のソースにおいて\qu{\MakeTabSkip}はタブ文字をあらわします．これは非
常に重要な点です．\prog{Make}での変数の定義は単純に
\begin{Syntax}
\va{変数}\str=\va{値}
\end{Syntax}
という書き方になります．同じ記述が何度も繰り返される場合はそれを変数とし
て定義できます．
\begin{Makefile}
MENDEX=mendex -d jisyo.dic -g
TEX=platex 
DVIPS=dvipsk -Pdl -t a4
DVIPDFM=dvipdfmx -f dlbase14.map -p a4 -V 4 -z 5
\end{Makefile}

{\LaTeX}では主となる原稿に対して章ごとに分割
されたファイルを \cmd{include}命令で読み込んで
いることがあるでしょう．この場合\prog{\LaTeX}
でタイプセットした後に生成されるDVIファイル
\Va{file}{dvi}は主となる原稿\Va{file}{tex}と
分割されたファイルに依存することになります．
{\LaTeX}には中途ファイルである
\Va{file}{aux}が使われています．{\LaTeX}自身も
タイプセットを完全なものにするために\Va{file}{aux}
が変更されたかどうかを検査します．この\Va{file}{aux}
が前回のタイプセットから変更されていない場合は
タイプセットが完了したとみなされます．
ですから，この依存関係は次のようになります．
\begin{Syntax}
\Va{file}{dvi}: \Va{file}{aux}\\
\Va{file}{aux}: \Va{file}{tex}\\
\MakeTabSkip platex \va{file}
\end{Syntax}
具体的には次のように記述します．
\begin{Makefile}
FILE=hoge
TEX=platex
all: $(FILE).dvi
$(FILE).dvi: $(FILE).aux
	platex $(FILE)
$(FILE).aux: $(FILE).tex
	platex $(FILE)
\end{Makefile}
%$
変数を使う場合は\qu{\texttt{\$}}を先頭にし
変数名を丸括弧で括ります．上記のような例は
ちょっとうまく行きません．\Va{file}{dvi}を
作成するのに毎回タイプセットが行われます．
これは\Va{file}{log}に相互参照に関する変更が
あるかどうかを調べるだけにするほうが良いでしょう．
次のような\Fl{Makefile}を作成するともう少しうまく行きます．
\fl{Makefile}中でシャープ\qu{\str{#}}以降はコメント
になります．
\begin{Makefile}
#主となる原稿
FILE=hoge
TEX=platex
REFGREP=grep "^LaTeX Warning: Label(s) may have changed."
all: $(FILE).dvi
$(FILE).dvi: $(FILE).aux
	(while $(REFGREP)$ $(FILE).log; do $(TEX) $(FILE); done)
$(FILE).aux: $(FILE).tex
	$(TEX) $(FILE)
\end{Makefile}
%$
\prog{Make}で使われるファイルには
\qu{\Fl{Makefile}}という決まった名前を
付けます．この\qu{\Fl{Makefile}}をタイプセット
したい\Va{file}{tex}と同じ場所におきます．
後は端末などから
\begin{InTerm}
   \type{make} 
\end{InTerm}
とすると\Va{file}{dvi}が作成されるので1度
やってみると良いでしょう．

原稿を作成しているときは\Va{file}{aux}とか
\Va{file}{log}や\Va{file}{toc}などが中途ファイルなので
タイプセット後には必要ありませんから，これを一括で
削除できると良いでしょう．
\begin{Makefile}
clean:	
	rm -f $(FILE).aux $(FILE).log $(FILE).toc $(FILE).tex~
\end{Makefile}
\Prog{Emacs}などを使っているときは\Va{file}{tex\~}も
削除してくれると有り難いでしょう．上記の2行を
先程の\fl{Makefile}に追加しましょう．

原稿が複数に分割されている場合は\Va{file1}{tex}，
\Va{file2}{tex}，\Va{file3}{tex}，\Va{file4}{tex}など
複数ありますからこれを次のように定義しておきます．
\begin{Makefile}
SRC=file1.tex file2.tex file3.tex file4.tex 
\end{Makefile}
これらのファイルが\Va{file}{aux}に依存することは
\begin{Makefile}
SRC=file1.tex file2.tex file3.tex file4.tex 
$(FILE).aux: $(FILE).tex $(SRC)
	      $(TEX) $(FILE)
\end{Makefile}
と書くことができます．%$
参考文献データベースが複数ある場合も同じように
行いますので
\begin{Makefile}
REF=biblio1.bib biblio2.bib biblio3.bib
$(FILE).aux: $(FILE).tex $(SRC) $(REF)
	      $(TEX) $(FILE)
\end{Makefile}
のようにします．

最終的に成形したいファイルがDVIファイル\Va{file}{dvi}
だけではなくPDFファイル\Va{file}{pdf}や{\PS}ファイル
\Va{file}{ps}も作成するときは\Va{file}{dvi}に依存させて，
成形手順を書きます．普通\Va{file}{pdf}や
\Va{file}{ps}も\Va{file}{dvi}を成形してから作成します．
\prog{pdf\LaTeX}などを使っているならば\Va{file}{tex}から
\Va{file}{pdf}にいきなり変換されますから，この場合は
\Va{file}{pdf}を\Va{file}{tex}に依存させて適切な
処理内容を記述します．最終的に\Va{file}{ps}と
\Va{file}{pdf}を作成するならば以下のように記述できます．
\begin{Makefile}
TEX =platex 
DVIPS =dvipsk -Pdl -t a4 -o $(FILE).ps
DVIPDFM=dvipdfmx -f dlbase14.map -p a4 -V 4 -z 5 -o $(FILE).pdf
all: $(FILE).pdf 
$(FILE).pdf: $(FILE).dvi
	      $(DVIPDFM) $(FILE)
$(FILE).ps:  $(FILE).dvi
	      $(DVIPS) $(FILE)
\end{Makefile}
%$

おまけとして関係するファイルを一つのTAR書庫に
まとめて\Prog{gzip}で圧縮することを考えましょう．
これには書庫を作成するための作業用のディレクトリ
\fl{\$(FILE)src/}を作成すると簡単です．マクロパッケージや
索引用のスタイルなどの他のファイルは\qu{\str{OTHERS}}に
忘れずにまとめておきましょう．
\begin{Makefile}
#SRC=file1.tex file2.tex file3.tex file4.tex 
#OTHERS=mymacro.sty
#REF=biblio1.bib biblio2.bib biblio3.bib
#FILE=main
tar: $(FILE).tex $(SRC) $(OTHERS) $(REF) Makefile
	 mkdir -p $(FILE)src/
	 cp  $(FILE).tex $(SRC) $(OHTERS) $(REF) Makefile $(FILE)src/
	 tar czf $(FILE)src.tgz $(FILE)src/
	 rm -fr $(FILE)src
\end{Makefile}
関係する全てのファイルを\fl{\$(file)src}ディレクトリに%$
コピーします．次のそのディレクトリに対して\prog{tar}を
使って\fl{\$(file)src.tgz}を作成します．処理が終わったならば
作業用のディレクトリの中を全て削除して完了です．こうすると
\fl{\$(file)src.tgz}がディレクトリ付きの書庫として作成されます．

以上のようなことをレポート・論文作成時にも活用します．
少々長いのですが以下の記述を\fl{Makefile}にまとめます．
このファイルは\Fl{Makefile.gz}として私のウェブページに
置くことにします．
\begin{Makefile}
# Title: Makefile
# Date:  2004/03/28
# Name:  Thor Watanabe
# Mail:  thor@tex.dante.jp
# 主となる原稿
FILE	=sample
# 分割され，インクルードされているファイル
SRC	=#chap1.tex chap2.tex,..., chap<n>.tex
#スタイルファイルやクラスファイルなど
OHTERS	=#funthesis.cls mymacro.sty
# 画像などのバイナリファイル
IMG	=#hoge.eps capture1.jpg
#文献データベース，あるならば.
REF	=biblio.bib
#走らせるTeXプログラム
TEX=platex
# Red Hat の場合
#DVIPS	=pdvips -Ppdf
#XDVI	=pxdvi
# GNU Linux の場合
#DVIPS	=dvips -Ppdf
#XDVI	=xdvik
# Windowsの場合
DVIPS	=dvipsk -Pdl -t a4
XDVI	=dviout 
# dvipdfmx
DVIPDF  =dvipdfmx -p a4 -f dlbase14.map -o $(FILE).pdf 
# 相互参照の解消のため
REFGREP=grep "^LaTeX Warning: Label(s) may have changed."
# プリンタの設定
PRINTER=//server/printername
# 標準のターゲット
all:	$(FILE).ps $(FILE).pdf 
printps:  $(FILE).ps
	 lpr -P$(PRINTER) $(FILE).ps
printpdf:  $(PSFILE)
	 lpr -P$(PRINTER) $(FILE).ps
$(FILE).pdf: $(FILE).dvi
	 $(DVIPDF) $(FILE)
$(FILE).ps: $(FILE).dvi
	 $(DVIPS) -o $(FILE).ps $(FILE)
$(FILE).dvi: $(FILE).aux $(FILE).bbl
	 (while $(REFGREP) $(FILE).log; do $(TEX) $(FILE); done)
$(FILE).bbl: $(REFFILE)
	 $(BIBTEX) $(FILE)
$(FILE).aux: $(FILE).tex
	 $(TEX) $(FILE)
clean:
	 rm -f $(FILE).aux $(FILE).log $(FILE).toc $(FILE).dvi 
	 rm -f $(FILE).pdf $(FILE).tex~ $(FILE).lof $(FILE).lot
tar:
	 mkdir -p $(FILE)
	 cp $(SRC) $(OHTERS) $(REF) $(IMG) $(FILE).tex Makefile $(FILE)/
	 tar czf $(FILE)src.tgz $(FILE)/
	 rm -fr $(FILE)/
\end{Makefile}
適宜設定などに関してはご自分の環境やファイル状況に%$
合わせてください．

レポートなどのそれ程大規模ではない文書の場合は
次のようにします．
\begin{Makefile}
FILE=report
#SRC=file1.eps file2.eps
XDVI=xdvi
TEX=platex
all:	$(FILE).dvi
$(FILE).dvi: $(FILE).tex
	 platex $(FILE) && platex $(FILE) && platx $(FILE)
$(FILE).pdf: $(FILE).dvi
	 dvipdfmx -p a4 -o $(FILE).pdf $(FILE)
clean:	
	 rm $(FILE).aux $(FILE).log $(FILE).tex~ 
view:	$(FILE).dvi
	 $(XDVI) $(FILE) &
tar:
	 mkdir -p $(FILE)src/
	 cp $(FILE).tex Makefile $(SRC) $(FILE)src/
	 tar czf $(FILE)src.tgz $(FILE)src/
	 rm -fr $(FILE)src/
\end{Makefile}
上記のファイルを作成しておけば
\begin{InTerm}
   \type{make view}
\end{InTerm}
とすると\fl{report.tex}の変更に併せて
タイプセットをしてから\fl{hoge.dvi}を表示し，
\begin{InTerm}
   \type{make tar}
\end{InTerm}
とするとそのときのレポートに関連するファイルを
\fl{reportsrc.tgz}として書庫化してくれます．そ
のためにはあらかじめ
\begin{Makefile}
SRC=file1.eps file2.eps 
\end{Makefile}
のように関係ファイルを\str{SRC}に指定します．何度も何度も
\begin{InTerm}
   \type{platex report.tex}
   \type{dvipdfmx reprot.dvi}
\end{InTerm}
と打ち込むのは今日でグッバイです．昨日までの自分とは
違う自分に出会えます，多分，多分です．
%"
